"""Replace approval_status with email verification

Revision ID: 3703816b42a2
Revises: 64bf417d72ff
Create Date: 2025-10-01 10:13:15.618290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3703816b42a2'
down_revision: Union[str, None] = '64bf417d72ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns for email verification
    op.add_column('users', sa.Column('email_verified',
                  sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('users', sa.Column('verification_token',
                  sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('verification_token_expires',
                  sa.DateTime(timezone=True), nullable=True))

    # Set existing users as verified (they were previously approved)
    op.execute(
        "UPDATE users SET email_verified = 1 WHERE approval_status = 'APPROVED'")
    op.execute(
        "UPDATE users SET email_verified = 0 WHERE approval_status != 'APPROVED'")

    # Update role column type
    op.alter_column('users', 'role',
                    existing_type=sa.VARCHAR(length=7),
                    type_=sa.Enum('DEVELOPER', 'SUPPORT', 'IT',
                                  'MANAGER', 'ADMIN', 'CLIENT', name='userrole'),
                    existing_nullable=False)

    # Drop the old approval_status column
    op.drop_column('users', 'approval_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('approval_status',
                  sa.VARCHAR(length=8), nullable=True))
    op.alter_column('users', 'role',
                    existing_type=sa.Enum(
                        'DEVELOPER', 'SUPPORT', 'IT', 'MANAGER', 'ADMIN', 'CLIENT', name='userrole'),
                    type_=sa.VARCHAR(length=7),
                    existing_nullable=False)
    op.drop_column('users', 'verification_token_expires')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
