"""Add approval_status to users table

Revision ID: 64bf417d72ff
Revises: 
Create Date: 2025-09-30 16:58:00.464153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64bf417d72ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('approval_status', sa.Enum(
        'PENDING', 'APPROVED', 'REJECTED', name='userapprovalstatus'), nullable=True))

    # Set existing users as approved
    op.execute(
        "UPDATE users SET approval_status = 'APPROVED' WHERE approval_status IS NULL")

    # Make the column not null
    op.alter_column('users', 'approval_status', nullable=False)

    op.alter_column('users', 'role',
                    existing_type=sa.VARCHAR(length=7),
                    type_=sa.Enum('DEVELOPER', 'SUPPORT', 'IT',
                                  'MANAGER', 'ADMIN', 'CLIENT', name='userrole'),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
                    existing_type=sa.Enum(
                        'DEVELOPER', 'SUPPORT', 'IT', 'MANAGER', 'ADMIN', 'CLIENT', name='userrole'),
                    type_=sa.VARCHAR(length=7),
                    existing_nullable=False)
    op.drop_column('users', 'approval_status')
    # ### end Alembic commands ###
